INSERT INTO `STATE` VALUES (1,'Assam'),
(2,'Jammu and Kashmir'),
(3,'Maharashtra'),
(4,'Uttar Pradesh'),
(5,'Gujrat'),
(6,'Andhra Pradesh'),
(7,'Karnataka'),
(8,'Kerala'),
(9,'West Bengal'),
(10,'Tripura'),
(11,'Chhattisgarh'),
(12,'Punjab'),
(13,'Mizoram'),
(14,'Rajasthan'),
(15,'Goa'),
(16,'Uttarakhand'),
(17,'Arunachal Pradesh'),
(18,'Bihar'),
(19,'Lakshadweep'),
(20,'Jharkhand'),
(21,'Dadra and Nagar Haveli'),
(22,'Orissa'),(23,'Tamil Nadu'),
(24,'Himachal Pradesh'),
(25,'Haryana'),
(26,'Madhya Pradesh'),
(27,'Delhi'),
(28,'Daman and Diu'),
(29,'Nagaland'),
(30,'Sikkim'),
(31,'Manipur'),
(32,'Meghalaya'),
(33,'Pondicherry'),
(34,'Andaman and Nicobar Islands');